# Generated by Django 2.1.3 on 2019-03-03 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190303_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book',
            new_name='title',
        ),
    ]
